name: nature_log_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

flutter:
  assets:
    - resources/
  uses-material-design: true

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  camera: ^0.11.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/ressources/nature_log_logo.jpg"

  flutter_lints: ^6.0.0


